"""Add new custom field columns for API structure

Revision ID: b2cdd89146b7
Revises: update_note_type_enum
Create Date: 2025-06-23 17:16:15.797330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2cdd89146b7'
down_revision = 'update_note_type_enum'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_fields', sa.Column('label', sa.String(length=255), nullable=True))
    op.add_column('custom_fields', sa.Column('field_name', sa.String(length=100), nullable=True))
    op.add_column('custom_fields', sa.Column('record_type', sa.String(length=50), nullable=True))
    op.add_column('custom_fields', sa.Column('default_value', sa.String(length=255), nullable=True))
    op.drop_constraint('orders_product_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_sales_affiliate_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_lead_affiliate_id_fkey', 'orders', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('orders_lead_affiliate_id_fkey', 'orders', 'affiliates', ['lead_affiliate_id'], ['id'])
    op.create_foreign_key('orders_sales_affiliate_id_fkey', 'orders', 'affiliates', ['sales_affiliate_id'], ['id'])
    op.create_foreign_key('orders_product_id_fkey', 'orders', 'products', ['product_id'], ['id'])
    op.drop_column('custom_fields', 'default_value')
    op.drop_column('custom_fields', 'record_type')
    op.drop_column('custom_fields', 'field_name')
    op.drop_column('custom_fields', 'label')
    # ### end Alembic commands ### 